
stages:
  - containers
  - builds
  - sanity_checks

.native_build_job:
  extends: .gitlab_native_build_job
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LIBDIR="$VROOT/lib"
    - export LD_LIBRARY_PATH="$LIBDIR"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
    - export TEST_MAINTAINER=1
    - eval `perl -V:archname`
    - export PERL5LIB="$VROOT/lib/perl5/$archname"
  script:
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt-perl.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - cd ../libvirt-perl
    - perl Build.PL install_base=$VROOT
    - perl Build
    - perl Build install
    - popd
    - perl Build.PL
    - perl Build
    - perl Build test
    - perl Build install
    - perl Build dist
    - if test -x /usr/bin/rpmbuild && test "$RPM" != "skip" ; then rpmbuild --nodeps -ta Sys-Virt-TCK*.tar.gz ; fi

include: '/ci/gitlab.yml'
